[build]
  publish = "project/dist"
  command = "cd project && npm run build"

[build.environment]
  # You can add environment variables here if needed

# Optional: You can add redirects, headers, or other configurations
[build.processing]
  skip_processing = true

# Optional: You can add functions configuration if needed
[functions]
  directory = "project/functions"