[build]
  publish = "project/dist"
  command = "cd project && npm run build"

[build.environment]
  # Add any environment variables here if needed
  # NODE_VERSION = "18"

[build.processing]
  skip_processing = true

# If you're using Netlify Functions, add this section
[functions]
  directory = "project/functions"

# If you need redirects, add them like this:
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# If you need headers, add them like this:
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"